### PR TITLE
Expr: 1165 Prevent TZ names appearing in lowercase

### PR DESCRIPTION
**Pull request by robert-craig-houston**
### Issue:
https://devtopia.esri.com/runtime/arcade/issues/1165

### Description

Previous change to allow case insensitive lookup of TZ altered the Date TZDB structure. This caused all TZ names to appear in lower case. Not ideal.

Rather than store additional information I took the path of least resistance and lowercase the strings on the fly. The Zone list is now sorted by lowercase as well. In future I plan on doing some benchmarking of this code and optimise any pain points here. In particular this list being sorted at runtime of the first script using isn't fantastic. The next logical step would be pre-preparing the TZDB to avoid this.

### CODE REVIEW

**Review by chri7325 — APPROVED** [review]

**Comment by robert-craig-houston** [comment]
vtest: https://runtime-rtc.esri.com/view/vTest/job/vtest/job/3rdparty-interface/518/

**Comment by robert-craig-houston** [comment]
Mac and Linux decided they didn't want to archive their build results. IOS and Android couldn't fetch other 3rd party libraries.

I asked again nicely: https://runtime-rtc.esri.com/view/vTest/job/vtest/job/3rdparty-interface/519/

**Comment by robert-craig-houston** [comment]
Linux and android now failing to fetch 3rd party... Dumb luck?

Retried them, hopefully they find them this time

**Comment by chri7325** [comment]
@robert-craig-houston when targetting a single 3rdparty library, it is usually best to clear out the `default` variable so you don't build all of 3rdparty and just date. Unfortunately GitHub will shut down cloning when too many are requested at once.

**Comment by robert-craig-houston** [comment]
Gotcha, thanks for the spot!

**Comment by robert-craig-houston** [comment]
3rd party vtest: https://runtime-rtc.esri.com/view/vTest/job/vtest/job/3rdparty-interface/520/downstreambuildview/
RTC vtest: https://runtime-rtc.esri.com/view/vTest/job/vtest/job/runtimecore-interface/10913/
Will also run a debug build on arm64 due to the previous problem, once the test build has passed.

**Comment by robert-craig-houston** [comment]
Vtest failures due to a missing spec file from https://devtopia.esri.com/WebGIS/arcgis-arcade-tests.

Seemed to trigger a segfault!

**Comment by chri7325** [comment]
@cwarner-8702 is this something that is a known issue?

**Comment by cwarner-8702** [comment]
I have not seen a segfault due to missing spec files in the `Json_domain_tests`, which I believe are the only tests using them.

@robert-craig-houston What file is missing?  What test is running?

**Comment by robert-craig-houston** [comment]
In the linux vtest the following result appeared: https://runtime-rtc.esri.com/view/vTest/job/vtest/job/runtimecore-linux/11290/parsed_console/

>  ===== Running the expression_unit_tests tests =====
>  /home/apptest/jenkins/workspace/vtest/runtimecore-linux/output/linux_x64_test/bin/expression_unit_tests --out=/home/apptest/jenkins/workspace/vtest/runtimecore-linux/results --data=/home/apptest/vtest/data --test=* --sandbox  
> 
> libc++abi: terminating with uncaught exception of type std::runtime_error: Cannot find test schema file: /home/apptest/jenkins/workspace/vtest/runtimecore-linux/3rdparty/arcgis-arcade-tests/tests/specs/featureset/domain_feature.spec.json
> 
> addr2line: DWARF error: section .debug_info is larger than its filesize! (0x93ef57 vs 0x530ea0)
> 
> addr2line: DWARF error: section .debug_info is larger than its filesize! (0x93ef57 vs 0x530ea0)
> 
> FATAL: SIGABRT: usually caused by an abort() or assert()

First time seeing this myself as well. I believe the misbehaving test is [here:](https://devtopia.esri.com/runtime/runtimecore/blob/main/test/expression/json_arcade_runner_test.h)

**Comment by robert-craig-houston** [comment]
Thanks again both!

3rdVtest: https://runtime-rtc.esri.com/view/vTest/job/vtest/job/3rdparty-interface/530/
RTC vtest: https://runtime-rtc.esri.com/view/vTest/job/vtest/job/runtimecore-interface/11112/

**Pull request merged**
